### ISSUE TITLE
[FEATURE] Split PPL tool into two tools for generate and execute

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/skills#138]
**Is your feature request related to a problem?**
The current PPL tool implementation will execute PPL as well

https://github.com/opensearch-project/skills/blob/e278d8d6a258dde3447c6d8b72ea88bc723f87f9/src/main/java/org/opensearch/agent/tools/PPLTool.java#L172

This can be useful for chat, where it would need the query response to reply to the user. But for query assist in event analytics observability plugin, the PPL tool is only used to generate the query, execution will be covered by event analytics. This allows UI to make any additional modifications to the query. It's ok to just ignore PPL execution results from PPL tool, but it's extra overhead and a bit unreliable since sometimes we need to extract the original PPL from error messages 
https://github.com/opensearch-project/skills/blob/e278d8d6a258dde3447c6d8b72ea88bc723f87f9/src/main/java/org/opensearch/agent/tools/PPLTool.java#L187

**What solution would you like?**
Split PPL tool into two parts, one for generate, one for execute

**What alternatives have you considered?**

**Do you have any additional context?**
cc @xinyual

**Comment by xinyual** [comment]
Add one more field to solve this issue. Pass `"execute": false` when you register Tool
