### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by ramda1234786** [opensearch-project/skills#174]
[Enquiry] How to get the documentation for this tool to do PPL from natural language and to do RAG

As i do not see any documentation on this tool

Thanks

RamDa

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/krisfreedain) [3](https://github.com/gkamat) [4](https://github.com/andrross) [5](https://github.com/getsaurabh02)

**Comment by zane-neo** [comment]
Please refer: https://github.com/opensearch-project/ml-commons/blob/main/docs/tutorials/agent_framework/build_your_own_chatbot.md and https://github.com/opensearch-project/ml-commons/blob/main/docs/tutorials/agent_framework/Chatbot_with_RAG.md
