### ISSUE TITLE
[BUG] 2.13 branch build failure

### ISSUE THREAD

**Issue by zane-neo** [opensearch-project/skills#277]
**What is the bug?**
When OpenSearch 2.13 releases, skills repo 2.13 branch build failed, more details can be found here: https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/8053/pipeline.

**How can one reproduce the bug?**
1. Checkout 2.13 branch at commit: a7c8b442a886fa49c67710d55ee7aa01aafef93a
2. Run ./gradlew build -Dos.arch=x86_64 under skills repo
3. See error

**What is the expected behavior?**
The build should be succeed

**What is your host/environment?**
 - OS: MacOS
 - 14.3.1 

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)

**Comment by zane-neo** [comment]
Closing this issue as 2.13 has released
