### ISSUE TITLE
[BUG] Fix flaky IT test

### ISSUE THREAD

**Issue by zane-neo** [opensearch-project/skills#331]
**What is the bug?**
https://github.com/opensearch-project/skills/actions/runs/9510352386/job/26214689845?pr=330#step:5:571, this IT fails time to time, we need to figure out the root cause and fix this.

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by dblock** [comment]
[Catch All Triage - Attendees [1](https://github.com/dblock/), [2](https://github.com/krisfreedain), [3](https://github.com/andrross), [4](https://github.com/gkamat), [5](https://github.com/getsaurabh02)]

**Comment by dblock** [comment]
@zane-neo Did the linked PR fix the issue? Can this be closed?

**Comment by zane-neo** [comment]
This has been fixed and closing it now.
