### ISSUE TITLE
Add skills repo to opensearch-build 3.0.0 manifest

### ISSUE THREAD

**Issue by ruanyl** [opensearch-project/skills#411]
## Description
Currently, skills repo is missing from OpenSearch 3.0.0 manifest, so OpenSearch 3.0.0 nightly build doesn't contain `opensearch-skills` plugin. We should add it to 3.0.0 manifest.

[opensearch-build 3.0.0 manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/3.0.0/opensearch-3.0.0.yml)

cc @zane-neo @yuye-aws @xinyual

**Comment by yuye-aws** [comment]
Raised a PR: https://github.com/opensearch-project/opensearch-build/pull/5052

**Comment by yuye-aws** [comment]
PR gets merged. Can you close this issue? @ruanyl

**Comment by dblock** [comment]
Closing via opensearch-build#5052.
