### ISSUE TITLE
[FEATURE] Support other model types in CreateAlertTool and CreateAnomalyDetectorTool

### ISSUE THREAD

**Issue by yuye-aws** [opensearch-project/skills#447]
**Is your feature request related to a problem?**
CreateAlertTool and CreateAnomalyDetectorTool only supports Claude and OpenAI as the model types. We need to support more model types. Just like: https://opensearch.org/docs/latest/ml-commons-plugin/remote-models/connectors/.

**What solution would you like?**
Refer to the connector and model interface in ml commons. Model interface document: https://opensearch.org/docs/latest/ml-commons-plugin/api/model-apis/register-model/.

**What alternatives have you considered?**
I'll look into the current implementation of connector and model interface. We'll reach a conclusion after discussing with tool owner @gaobinlong and @qianheng-aws. 

**Do you have any additional context?**
These 2 tools needs `model_type` parameter due to prompt customization.

**Comment by yuye-aws** [comment]
Please assign this issue to me thanks!

**Comment by zane-neo** [comment]
I suggest we can make this a flexible implementation which can adapt to more and more models automatically w/o blocking user's integration.

**Comment by yuye-aws** [comment]
> I suggest we can make this a flexible implementation which can adapt to more and more models automatically w/o blocking user's integration.

Agreed. The `CreateAnomalyDetectorTool` now supports every `model_type` with the `prompt` parameter. The `CreateAlertTool` can follow the existing implementation of `CreateAnomalyDetectorTool`.

**Comment by yuye-aws** [comment]
Hi @gaobinlong ! Do you think [the comment](https://github.com/opensearch-project/skills/pull/452) also makes sense for **CreateAnomalyDetectorTool**? If so, can you create a small PR to fix it?

**Comment by dblock** [comment]
[[Catch All Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta), [3](https://github.com/andrross/), [4](https://github.com/dolla24)]
